// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  symbol: __t.string(),
  open: __t.string(),
  high: __t.string(),
  low: __t.string(),
  close: __t.string(),
  volume: __t.string(),
  quoteVolume: __t.string().name("quote_volume"),
  tradeCount: __t.i64().name("trade_count"),
  openTime: __t.i64().name("open_time"),
  closeTime: __t.i64().name("close_time"),
  isClosed: __t.bool().name("is_closed"),
});
