// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  symbol: __t.string().primaryKey(),
  bestBidPrice: __t.string().name("best_bid_price"),
  bestBidQty: __t.string().name("best_bid_qty"),
  bestAskPrice: __t.string().name("best_ask_price"),
  bestAskQty: __t.string().name("best_ask_qty"),
  updateId: __t.i64().name("update_id"),
});
