// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  symbol: __t.string().primaryKey(),
  price: __t.string(),
  quantity: __t.string(),
  tradeTime: __t.i64().name("trade_time"),
  aggTradeId: __t.i64().name("agg_trade_id"),
  isBuyerMaker: __t.bool().name("is_buyer_maker"),
});
