// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  symbol: __t.string(),
  interval: __t.string(),
  open: __t.string(),
  high: __t.string(),
  low: __t.string(),
  close: __t.string(),
  volume: __t.string(),
  quoteVolume: __t.string(),
  tradeCount: __t.i64(),
  openTime: __t.i64(),
  closeTime: __t.i64(),
  isClosed: __t.bool(),
};
