// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  symbol: __t.string(),
  bestBidPrice: __t.string(),
  bestBidQty: __t.string(),
  bestAskPrice: __t.string(),
  bestAskQty: __t.string(),
  updateId: __t.i64(),
};
