// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const LiveBookTicker = __t.object("LiveBookTicker", {
  symbol: __t.string(),
  bestBidPrice: __t.string(),
  bestBidQty: __t.string(),
  bestAskPrice: __t.string(),
  bestAskQty: __t.string(),
  updateId: __t.i64(),
});
export type LiveBookTicker = __Infer<typeof LiveBookTicker>;

export const LiveKline = __t.object("LiveKline", {
  id: __t.string(),
  symbol: __t.string(),
  barInterval: __t.string(),
  open: __t.string(),
  high: __t.string(),
  low: __t.string(),
  close: __t.string(),
  volume: __t.string(),
  quoteVolume: __t.string(),
  tradeCount: __t.i64(),
  openTime: __t.i64(),
  closeTime: __t.i64(),
  isClosed: __t.bool(),
});
export type LiveKline = __Infer<typeof LiveKline>;

export const LiveKlineSecond = __t.object("LiveKlineSecond", {
  id: __t.string(),
  symbol: __t.string(),
  open: __t.string(),
  high: __t.string(),
  low: __t.string(),
  close: __t.string(),
  volume: __t.string(),
  quoteVolume: __t.string(),
  tradeCount: __t.i64(),
  openTime: __t.i64(),
  closeTime: __t.i64(),
  isClosed: __t.bool(),
});
export type LiveKlineSecond = __Infer<typeof LiveKlineSecond>;

export const LiveTrade = __t.object("LiveTrade", {
  symbol: __t.string(),
  price: __t.string(),
  quantity: __t.string(),
  tradeTime: __t.i64(),
  aggTradeId: __t.i64(),
  isBuyerMaker: __t.bool(),
});
export type LiveTrade = __Infer<typeof LiveTrade>;

