// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LiveBookTicker {
    pub symbol: String,
    pub best_bid_price: String,
    pub best_bid_qty: String,
    pub best_ask_price: String,
    pub best_ask_qty: String,
    pub update_id: i64,
}

impl __sdk::InModule for LiveBookTicker {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LiveBookTicker`.
///
/// Provides typed access to columns for query building.
pub struct LiveBookTickerCols {
    pub symbol: __sdk::__query_builder::Col<LiveBookTicker, String>,
    pub best_bid_price: __sdk::__query_builder::Col<LiveBookTicker, String>,
    pub best_bid_qty: __sdk::__query_builder::Col<LiveBookTicker, String>,
    pub best_ask_price: __sdk::__query_builder::Col<LiveBookTicker, String>,
    pub best_ask_qty: __sdk::__query_builder::Col<LiveBookTicker, String>,
    pub update_id: __sdk::__query_builder::Col<LiveBookTicker, i64>,
}

impl __sdk::__query_builder::HasCols for LiveBookTicker {
    type Cols = LiveBookTickerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LiveBookTickerCols {
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            best_bid_price: __sdk::__query_builder::Col::new(table_name, "best_bid_price"),
            best_bid_qty: __sdk::__query_builder::Col::new(table_name, "best_bid_qty"),
            best_ask_price: __sdk::__query_builder::Col::new(table_name, "best_ask_price"),
            best_ask_qty: __sdk::__query_builder::Col::new(table_name, "best_ask_qty"),
            update_id: __sdk::__query_builder::Col::new(table_name, "update_id"),
        }
    }
}

/// Indexed column accessor struct for the table `LiveBookTicker`.
///
/// Provides typed access to indexed columns for query building.
pub struct LiveBookTickerIxCols {
    pub symbol: __sdk::__query_builder::IxCol<LiveBookTicker, String>,
}

impl __sdk::__query_builder::HasIxCols for LiveBookTicker {
    type IxCols = LiveBookTickerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LiveBookTickerIxCols {
            symbol: __sdk::__query_builder::IxCol::new(table_name, "symbol"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LiveBookTicker {}
