// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_kline_second_type::LiveKlineSecond;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_kline_second`.
///
/// Obtain a handle from the [`LiveKlineSecondTableAccess::live_kline_second`] method on [`super::RemoteTables`],
/// like `ctx.db.live_kline_second()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_kline_second().on_insert(...)`.
pub struct LiveKlineSecondTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiveKlineSecond>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_kline_second`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiveKlineSecondTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiveKlineSecondTableHandle`], which mediates access to the table `live_kline_second`.
    fn live_kline_second(&self) -> LiveKlineSecondTableHandle<'_>;
}

impl LiveKlineSecondTableAccess for super::RemoteTables {
    fn live_kline_second(&self) -> LiveKlineSecondTableHandle<'_> {
        LiveKlineSecondTableHandle {
            imp: self.imp.get_table::<LiveKlineSecond>("live_kline_second"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiveKlineSecondInsertCallbackId(__sdk::CallbackId);
pub struct LiveKlineSecondDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiveKlineSecondTableHandle<'ctx> {
    type Row = LiveKlineSecond;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiveKlineSecond> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiveKlineSecondInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveKlineSecondInsertCallbackId {
        LiveKlineSecondInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiveKlineSecondInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiveKlineSecondDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveKlineSecondDeleteCallbackId {
        LiveKlineSecondDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiveKlineSecondDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LiveKlineSecondUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiveKlineSecondTableHandle<'ctx> {
    type UpdateCallbackId = LiveKlineSecondUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiveKlineSecondUpdateCallbackId {
        LiveKlineSecondUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiveKlineSecondUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `live_kline_second`,
/// which allows point queries on the field of the same name
/// via the [`LiveKlineSecondIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_kline_second().id().find(...)`.
pub struct LiveKlineSecondIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiveKlineSecond, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiveKlineSecondTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `live_kline_second`.
    pub fn id(&self) -> LiveKlineSecondIdUnique<'ctx> {
        LiveKlineSecondIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiveKlineSecondIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LiveKlineSecond> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiveKlineSecond>("live_kline_second");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LiveKlineSecond>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiveKlineSecond>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LiveKlineSecond`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_kline_secondQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LiveKlineSecond`.
    fn live_kline_second(&self) -> __sdk::__query_builder::Table<LiveKlineSecond>;
}

impl live_kline_secondQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_kline_second(&self) -> __sdk::__query_builder::Table<LiveKlineSecond> {
        __sdk::__query_builder::Table::new("live_kline_second")
    }
}
