// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LiveKlineSecond {
    pub id: String,
    pub symbol: String,
    pub open: String,
    pub high: String,
    pub low: String,
    pub close: String,
    pub volume: String,
    pub quote_volume: String,
    pub trade_count: i64,
    pub open_time: i64,
    pub close_time: i64,
    pub is_closed: bool,
}

impl __sdk::InModule for LiveKlineSecond {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LiveKlineSecond`.
///
/// Provides typed access to columns for query building.
pub struct LiveKlineSecondCols {
    pub id: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub symbol: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub open: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub high: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub low: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub close: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub volume: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub quote_volume: __sdk::__query_builder::Col<LiveKlineSecond, String>,
    pub trade_count: __sdk::__query_builder::Col<LiveKlineSecond, i64>,
    pub open_time: __sdk::__query_builder::Col<LiveKlineSecond, i64>,
    pub close_time: __sdk::__query_builder::Col<LiveKlineSecond, i64>,
    pub is_closed: __sdk::__query_builder::Col<LiveKlineSecond, bool>,
}

impl __sdk::__query_builder::HasCols for LiveKlineSecond {
    type Cols = LiveKlineSecondCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LiveKlineSecondCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            open: __sdk::__query_builder::Col::new(table_name, "open"),
            high: __sdk::__query_builder::Col::new(table_name, "high"),
            low: __sdk::__query_builder::Col::new(table_name, "low"),
            close: __sdk::__query_builder::Col::new(table_name, "close"),
            volume: __sdk::__query_builder::Col::new(table_name, "volume"),
            quote_volume: __sdk::__query_builder::Col::new(table_name, "quote_volume"),
            trade_count: __sdk::__query_builder::Col::new(table_name, "trade_count"),
            open_time: __sdk::__query_builder::Col::new(table_name, "open_time"),
            close_time: __sdk::__query_builder::Col::new(table_name, "close_time"),
            is_closed: __sdk::__query_builder::Col::new(table_name, "is_closed"),
        }
    }
}

/// Indexed column accessor struct for the table `LiveKlineSecond`.
///
/// Provides typed access to indexed columns for query building.
pub struct LiveKlineSecondIxCols {
    pub id: __sdk::__query_builder::IxCol<LiveKlineSecond, String>,
    pub symbol: __sdk::__query_builder::IxCol<LiveKlineSecond, String>,
}

impl __sdk::__query_builder::HasIxCols for LiveKlineSecond {
    type IxCols = LiveKlineSecondIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LiveKlineSecondIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            symbol: __sdk::__query_builder::IxCol::new(table_name, "symbol"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LiveKlineSecond {}
