// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LiveTrade {
    pub symbol: String,
    pub price: String,
    pub quantity: String,
    pub trade_time: i64,
    pub agg_trade_id: i64,
    pub is_buyer_maker: bool,
}

impl __sdk::InModule for LiveTrade {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LiveTrade`.
///
/// Provides typed access to columns for query building.
pub struct LiveTradeCols {
    pub symbol: __sdk::__query_builder::Col<LiveTrade, String>,
    pub price: __sdk::__query_builder::Col<LiveTrade, String>,
    pub quantity: __sdk::__query_builder::Col<LiveTrade, String>,
    pub trade_time: __sdk::__query_builder::Col<LiveTrade, i64>,
    pub agg_trade_id: __sdk::__query_builder::Col<LiveTrade, i64>,
    pub is_buyer_maker: __sdk::__query_builder::Col<LiveTrade, bool>,
}

impl __sdk::__query_builder::HasCols for LiveTrade {
    type Cols = LiveTradeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LiveTradeCols {
            symbol: __sdk::__query_builder::Col::new(table_name, "symbol"),
            price: __sdk::__query_builder::Col::new(table_name, "price"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            trade_time: __sdk::__query_builder::Col::new(table_name, "trade_time"),
            agg_trade_id: __sdk::__query_builder::Col::new(table_name, "agg_trade_id"),
            is_buyer_maker: __sdk::__query_builder::Col::new(table_name, "is_buyer_maker"),
        }
    }
}

/// Indexed column accessor struct for the table `LiveTrade`.
///
/// Provides typed access to indexed columns for query building.
pub struct LiveTradeIxCols {
    pub symbol: __sdk::__query_builder::IxCol<LiveTrade, String>,
}

impl __sdk::__query_builder::HasIxCols for LiveTrade {
    type IxCols = LiveTradeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LiveTradeIxCols {
            symbol: __sdk::__query_builder::IxCol::new(table_name, "symbol"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LiveTrade {}
