// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_kline_type::LiveKline;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_kline`.
///
/// Obtain a handle from the [`LiveKlineTableAccess::live_kline`] method on [`super::RemoteTables`],
/// like `ctx.db.live_kline()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_kline().on_insert(...)`.
pub struct LiveKlineTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiveKline>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_kline`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiveKlineTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiveKlineTableHandle`], which mediates access to the table `live_kline`.
    fn live_kline(&self) -> LiveKlineTableHandle<'_>;
}

impl LiveKlineTableAccess for super::RemoteTables {
    fn live_kline(&self) -> LiveKlineTableHandle<'_> {
        LiveKlineTableHandle {
            imp: self.imp.get_table::<LiveKline>("live_kline"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiveKlineInsertCallbackId(__sdk::CallbackId);
pub struct LiveKlineDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiveKlineTableHandle<'ctx> {
    type Row = LiveKline;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiveKline> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiveKlineInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveKlineInsertCallbackId {
        LiveKlineInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiveKlineInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiveKlineDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveKlineDeleteCallbackId {
        LiveKlineDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiveKlineDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LiveKlineUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiveKlineTableHandle<'ctx> {
    type UpdateCallbackId = LiveKlineUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiveKlineUpdateCallbackId {
        LiveKlineUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiveKlineUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `live_kline`,
/// which allows point queries on the field of the same name
/// via the [`LiveKlineIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_kline().id().find(...)`.
pub struct LiveKlineIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiveKline, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiveKlineTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `live_kline`.
    pub fn id(&self) -> LiveKlineIdUnique<'ctx> {
        LiveKlineIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiveKlineIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LiveKline> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiveKline>("live_kline");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LiveKline>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiveKline>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LiveKline`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_klineQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LiveKline`.
    fn live_kline(&self) -> __sdk::__query_builder::Table<LiveKline>;
}

impl live_klineQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_kline(&self) -> __sdk::__query_builder::Table<LiveKline> {
        __sdk::__query_builder::Table::new("live_kline")
    }
}
