// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_trade_type::LiveTrade;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_trade`.
///
/// Obtain a handle from the [`LiveTradeTableAccess::live_trade`] method on [`super::RemoteTables`],
/// like `ctx.db.live_trade()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_trade().on_insert(...)`.
pub struct LiveTradeTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiveTrade>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_trade`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiveTradeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiveTradeTableHandle`], which mediates access to the table `live_trade`.
    fn live_trade(&self) -> LiveTradeTableHandle<'_>;
}

impl LiveTradeTableAccess for super::RemoteTables {
    fn live_trade(&self) -> LiveTradeTableHandle<'_> {
        LiveTradeTableHandle {
            imp: self.imp.get_table::<LiveTrade>("live_trade"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiveTradeInsertCallbackId(__sdk::CallbackId);
pub struct LiveTradeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiveTradeTableHandle<'ctx> {
    type Row = LiveTrade;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiveTrade> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiveTradeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveTradeInsertCallbackId {
        LiveTradeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiveTradeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiveTradeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveTradeDeleteCallbackId {
        LiveTradeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiveTradeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LiveTradeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiveTradeTableHandle<'ctx> {
    type UpdateCallbackId = LiveTradeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiveTradeUpdateCallbackId {
        LiveTradeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiveTradeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `symbol` unique index on the table `live_trade`,
/// which allows point queries on the field of the same name
/// via the [`LiveTradeSymbolUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_trade().symbol().find(...)`.
pub struct LiveTradeSymbolUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiveTrade, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiveTradeTableHandle<'ctx> {
    /// Get a handle on the `symbol` unique index on the table `live_trade`.
    pub fn symbol(&self) -> LiveTradeSymbolUnique<'ctx> {
        LiveTradeSymbolUnique {
            imp: self.imp.get_unique_constraint::<String>("symbol"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiveTradeSymbolUnique<'ctx> {
    /// Find the subscribed row whose `symbol` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LiveTrade> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiveTrade>("live_trade");
    _table.add_unique_constraint::<String>("symbol", |row| &row.symbol);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LiveTrade>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiveTrade>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LiveTrade`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_tradeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LiveTrade`.
    fn live_trade(&self) -> __sdk::__query_builder::Table<LiveTrade>;
}

impl live_tradeQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_trade(&self) -> __sdk::__query_builder::Table<LiveTrade> {
        __sdk::__query_builder::Table::new("live_trade")
    }
}
