// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::live_book_ticker_type::LiveBookTicker;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `live_book_ticker`.
///
/// Obtain a handle from the [`LiveBookTickerTableAccess::live_book_ticker`] method on [`super::RemoteTables`],
/// like `ctx.db.live_book_ticker()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_book_ticker().on_insert(...)`.
pub struct LiveBookTickerTableHandle<'ctx> {
    imp: __sdk::TableHandle<LiveBookTicker>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `live_book_ticker`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LiveBookTickerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LiveBookTickerTableHandle`], which mediates access to the table `live_book_ticker`.
    fn live_book_ticker(&self) -> LiveBookTickerTableHandle<'_>;
}

impl LiveBookTickerTableAccess for super::RemoteTables {
    fn live_book_ticker(&self) -> LiveBookTickerTableHandle<'_> {
        LiveBookTickerTableHandle {
            imp: self.imp.get_table::<LiveBookTicker>("live_book_ticker"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LiveBookTickerInsertCallbackId(__sdk::CallbackId);
pub struct LiveBookTickerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LiveBookTickerTableHandle<'ctx> {
    type Row = LiveBookTicker;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LiveBookTicker> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LiveBookTickerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveBookTickerInsertCallbackId {
        LiveBookTickerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LiveBookTickerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LiveBookTickerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LiveBookTickerDeleteCallbackId {
        LiveBookTickerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LiveBookTickerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LiveBookTickerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LiveBookTickerTableHandle<'ctx> {
    type UpdateCallbackId = LiveBookTickerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LiveBookTickerUpdateCallbackId {
        LiveBookTickerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LiveBookTickerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `symbol` unique index on the table `live_book_ticker`,
/// which allows point queries on the field of the same name
/// via the [`LiveBookTickerSymbolUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.live_book_ticker().symbol().find(...)`.
pub struct LiveBookTickerSymbolUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LiveBookTicker, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LiveBookTickerTableHandle<'ctx> {
    /// Get a handle on the `symbol` unique index on the table `live_book_ticker`.
    pub fn symbol(&self) -> LiveBookTickerSymbolUnique<'ctx> {
        LiveBookTickerSymbolUnique {
            imp: self.imp.get_unique_constraint::<String>("symbol"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LiveBookTickerSymbolUnique<'ctx> {
    /// Find the subscribed row whose `symbol` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<LiveBookTicker> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LiveBookTicker>("live_book_ticker");
    _table.add_unique_constraint::<String>("symbol", |row| &row.symbol);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LiveBookTicker>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LiveBookTicker>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LiveBookTicker`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait live_book_tickerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LiveBookTicker`.
    fn live_book_ticker(&self) -> __sdk::__query_builder::Table<LiveBookTicker>;
}

impl live_book_tickerQueryTableAccess for __sdk::QueryTableAccessor {
    fn live_book_ticker(&self) -> __sdk::__query_builder::Table<LiveBookTicker> {
        __sdk::__query_builder::Table::new("live_book_ticker")
    }
}
