// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordBookTickerArgs {
    pub symbol: String,
    pub best_bid_price: String,
    pub best_bid_qty: String,
    pub best_ask_price: String,
    pub best_ask_qty: String,
    pub update_id: i64,
}

impl From<RecordBookTickerArgs> for super::Reducer {
    fn from(args: RecordBookTickerArgs) -> Self {
        Self::RecordBookTicker {
            symbol: args.symbol,
            best_bid_price: args.best_bid_price,
            best_bid_qty: args.best_bid_qty,
            best_ask_price: args.best_ask_price,
            best_ask_qty: args.best_ask_qty,
            update_id: args.update_id,
        }
    }
}

impl __sdk::InModule for RecordBookTickerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_book_ticker`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_book_ticker {
    /// Request that the remote module invoke the reducer `record_book_ticker` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_book_ticker:record_book_ticker_then`] to run a callback after the reducer completes.
    fn record_book_ticker(
        &self,
        symbol: String,
        best_bid_price: String,
        best_bid_qty: String,
        best_ask_price: String,
        best_ask_qty: String,
        update_id: i64,
    ) -> __sdk::Result<()> {
        self.record_book_ticker_then(
            symbol,
            best_bid_price,
            best_bid_qty,
            best_ask_price,
            best_ask_qty,
            update_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_book_ticker` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_book_ticker_then(
        &self,
        symbol: String,
        best_bid_price: String,
        best_bid_qty: String,
        best_ask_price: String,
        best_ask_qty: String,
        update_id: i64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl record_book_ticker for super::RemoteReducers {
    fn record_book_ticker_then(
        &self,
        symbol: String,
        best_bid_price: String,
        best_bid_qty: String,
        best_ask_price: String,
        best_ask_qty: String,
        update_id: i64,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordBookTickerArgs {
                symbol,
                best_bid_price,
                best_bid_qty,
                best_ask_price,
                best_ask_qty,
                update_id,
            },
            callback,
        )
    }
}
