// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordTradeArgs {
    pub symbol: String,
    pub price: String,
    pub quantity: String,
    pub trade_time: i64,
    pub agg_trade_id: i64,
    pub is_buyer_maker: bool,
}

impl From<RecordTradeArgs> for super::Reducer {
    fn from(args: RecordTradeArgs) -> Self {
        Self::RecordTrade {
            symbol: args.symbol,
            price: args.price,
            quantity: args.quantity,
            trade_time: args.trade_time,
            agg_trade_id: args.agg_trade_id,
            is_buyer_maker: args.is_buyer_maker,
        }
    }
}

impl __sdk::InModule for RecordTradeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_trade`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_trade {
    /// Request that the remote module invoke the reducer `record_trade` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_trade:record_trade_then`] to run a callback after the reducer completes.
    fn record_trade(
        &self,
        symbol: String,
        price: String,
        quantity: String,
        trade_time: i64,
        agg_trade_id: i64,
        is_buyer_maker: bool,
    ) -> __sdk::Result<()> {
        self.record_trade_then(
            symbol,
            price,
            quantity,
            trade_time,
            agg_trade_id,
            is_buyer_maker,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_trade` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_trade_then(
        &self,
        symbol: String,
        price: String,
        quantity: String,
        trade_time: i64,
        agg_trade_id: i64,
        is_buyer_maker: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl record_trade for super::RemoteReducers {
    fn record_trade_then(
        &self,
        symbol: String,
        price: String,
        quantity: String,
        trade_time: i64,
        agg_trade_id: i64,
        is_buyer_maker: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordTradeArgs {
                symbol,
                price,
                quantity,
                trade_time,
                agg_trade_id,
                is_buyer_maker,
            },
            callback,
        )
    }
}
