// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordKlineSecondArgs {
    pub symbol: String,
    pub open: String,
    pub high: String,
    pub low: String,
    pub close: String,
    pub volume: String,
    pub quote_volume: String,
    pub trade_count: i64,
    pub open_time: i64,
    pub close_time: i64,
    pub is_closed: bool,
}

impl From<RecordKlineSecondArgs> for super::Reducer {
    fn from(args: RecordKlineSecondArgs) -> Self {
        Self::RecordKlineSecond {
            symbol: args.symbol,
            open: args.open,
            high: args.high,
            low: args.low,
            close: args.close,
            volume: args.volume,
            quote_volume: args.quote_volume,
            trade_count: args.trade_count,
            open_time: args.open_time,
            close_time: args.close_time,
            is_closed: args.is_closed,
        }
    }
}

impl __sdk::InModule for RecordKlineSecondArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_kline_second`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_kline_second {
    /// Request that the remote module invoke the reducer `record_kline_second` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_kline_second:record_kline_second_then`] to run a callback after the reducer completes.
    fn record_kline_second(
        &self,
        symbol: String,
        open: String,
        high: String,
        low: String,
        close: String,
        volume: String,
        quote_volume: String,
        trade_count: i64,
        open_time: i64,
        close_time: i64,
        is_closed: bool,
    ) -> __sdk::Result<()> {
        self.record_kline_second_then(
            symbol,
            open,
            high,
            low,
            close,
            volume,
            quote_volume,
            trade_count,
            open_time,
            close_time,
            is_closed,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `record_kline_second` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_kline_second_then(
        &self,
        symbol: String,
        open: String,
        high: String,
        low: String,
        close: String,
        volume: String,
        quote_volume: String,
        trade_count: i64,
        open_time: i64,
        close_time: i64,
        is_closed: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl record_kline_second for super::RemoteReducers {
    fn record_kline_second_then(
        &self,
        symbol: String,
        open: String,
        high: String,
        low: String,
        close: String,
        volume: String,
        quote_volume: String,
        trade_count: i64,
        open_time: i64,
        close_time: i64,
        is_closed: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordKlineSecondArgs {
                symbol,
                open,
                high,
                low,
                close,
                volume,
                quote_volume,
                trade_count,
                open_time,
                close_time,
                is_closed,
            },
            callback,
        )
    }
}
