// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RecordBookTickerReducer from "../record_book_ticker_reducer";
import RecordKlineReducer from "../record_kline_reducer";
import RecordTradeReducer from "../record_trade_reducer";

export type RecordBookTickerParams = __Infer<typeof RecordBookTickerReducer>;
export type RecordKlineParams = __Infer<typeof RecordKlineReducer>;
export type RecordTradeParams = __Infer<typeof RecordTradeReducer>;

